// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategoria(arg1, arg2) {
  return window['go']['main']['App']['CreateCategoria'](arg1, arg2);
}

export function CreateConta(arg1, arg2) {
  return window['go']['main']['App']['CreateConta'](arg1, arg2);
}

export function CreateLancamento(arg1) {
  return window['go']['main']['App']['CreateLancamento'](arg1);
}

export function DashboardResumo() {
  return window['go']['main']['App']['DashboardResumo']();
}

export function DeleteCategoria(arg1) {
  return window['go']['main']['App']['DeleteCategoria'](arg1);
}

export function DeleteConta(arg1) {
  return window['go']['main']['App']['DeleteConta'](arg1);
}

export function DeleteLancamento(arg1) {
  return window['go']['main']['App']['DeleteLancamento'](arg1);
}

export function Estornar(arg1) {
  return window['go']['main']['App']['Estornar'](arg1);
}

export function ExportarDRE(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportarDRE'](arg1, arg2, arg3);
}

export function ExportarFluxoCaixa(arg1, arg2) {
  return window['go']['main']['App']['ExportarFluxoCaixa'](arg1, arg2);
}

export function ExportarLancamentos(arg1, arg2) {
  return window['go']['main']['App']['ExportarLancamentos'](arg1, arg2);
}

export function ListCategorias() {
  return window['go']['main']['App']['ListCategorias']();
}

export function ListContas() {
  return window['go']['main']['App']['ListContas']();
}

export function ListLancamentos(arg1) {
  return window['go']['main']['App']['ListLancamentos'](arg1);
}

export function MarcarBaixa(arg1, arg2) {
  return window['go']['main']['App']['MarcarBaixa'](arg1, arg2);
}

export function RelatorioDRE(arg1, arg2) {
  return window['go']['main']['App']['RelatorioDRE'](arg1, arg2);
}

export function RelatorioFluxoCaixa(arg1) {
  return window['go']['main']['App']['RelatorioFluxoCaixa'](arg1);
}

export function UpdateConta(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConta'](arg1, arg2, arg3);
}

export function UpdateLancamento(arg1, arg2) {
  return window['go']['main']['App']['UpdateLancamento'](arg1, arg2);
}
