// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {updater} from '../models';

export function BaixarEAplicarAtualizacao():Promise<void>;

export function CreateCategoria(arg1:string,arg2:string):Promise<model.Categoria>;

export function CreateConta(arg1:string,arg2:number):Promise<model.Conta>;

export function CreateLancamento(arg1:model.LancamentoInput):Promise<model.Lancamento>;

export function DashboardResumo():Promise<main.Resumo>;

export function DeleteCategoria(arg1:number):Promise<void>;

export function DeleteConta(arg1:number):Promise<void>;

export function DeleteLancamento(arg1:number):Promise<void>;

export function Estornar(arg1:number):Promise<model.Lancamento>;

export function ExportarDRE(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportarFluxoCaixa(arg1:number,arg2:string):Promise<string>;

export function ExportarLancamentos(arg1:model.LancamentoFiltro,arg2:string):Promise<string>;

export function ListCategorias():Promise<Array<model.Categoria>>;

export function ListContas():Promise<Array<model.Conta>>;

export function ListLancamentos(arg1:model.LancamentoFiltro):Promise<Array<model.Lancamento>>;

export function MarcarBaixa(arg1:number,arg2:string):Promise<model.Lancamento>;

export function ReiniciarApp():Promise<void>;

export function RelatorioDRE(arg1:string,arg2:string):Promise<main.DRE>;

export function RelatorioFluxoCaixa(arg1:number):Promise<Array<main.FluxoCaixaLinha>>;

export function UpdateConta(arg1:number,arg2:string,arg3:number):Promise<model.Conta>;

export function UpdateLancamento(arg1:number,arg2:model.LancamentoInput):Promise<model.Lancamento>;

export function VerificarAtualizacao():Promise<updater.Atualizacao>;

export function VersaoAtual():Promise<string>;
